//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TouristRoutes.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TouristRoutes.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваши данные успешно сохранены!.
        /// </summary>
        internal static string AnketaDataSavedMessage {
            get {
                return ResourceManager.GetString("AnketaDataSavedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аутентификация прошла успешно!.
        /// </summary>
        internal static string AuthMessage {
            get {
                return ResourceManager.GetString("AuthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь с таким email уже есть.
        /// </summary>
        internal static string EmailRepeatMessage {
            get {
                return ResourceManager.GetString("EmailRepeatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неправильный формат email.
        /// </summary>
        internal static string EmailUncorrectMessage {
            get {
                return ResourceManager.GetString("EmailUncorrectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный пароль.
        /// </summary>
        internal static string PasswordInvalidMessage {
            get {
                return ResourceManager.GetString("PasswordInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ненадежный пароль.
        /// </summary>
        internal static string PasswordUnsecureMessage {
            get {
                return ResourceManager.GetString("PasswordUnsecureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регистрация прошла успешно!.
        /// </summary>
        internal static string RegisterMessage {
            get {
                return ResourceManager.GetString("RegisterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Маршрут добавлен!.
        /// </summary>
        internal static string RouteAddMessage {
            get {
                return ResourceManager.GetString("RouteAddMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтверждение удаления.
        /// </summary>
        internal static string RouteDeleteConfirm {
            get {
                return ResourceManager.GetString("RouteDeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уверены, что хотите удалить выбранный маршрут?.
        /// </summary>
        internal static string RouteDeleteConfirmMessage {
            get {
                return ResourceManager.GetString("RouteDeleteConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Маршрут удален!.
        /// </summary>
        internal static string RouteDeleteMessage {
            get {
                return ResourceManager.GetString("RouteDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Images.
        /// </summary>
        internal static string RoutePicturesFileName {
            get {
                return ResourceManager.GetString("RoutePicturesFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &quot;!@#$%^&amp;*()~`;:?&quot;.
        /// </summary>
        internal static string SpecialSymbols {
            get {
                return ResourceManager.GetString("SpecialSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не все теги найдены.
        /// </summary>
        internal static string TagsNotFindMessage {
            get {
                return ResourceManager.GetString("TagsNotFindMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текущий пользователь не вошел в систему.
        /// </summary>
        internal static string UserUnloggedMessage {
            get {
                return ResourceManager.GetString("UserUnloggedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет такого пользователя.
        /// </summary>
        internal static string UserUnregisterMessage {
            get {
                return ResourceManager.GetString("UserUnregisterMessage", resourceCulture);
            }
        }
    }
}
